(focus MAIN)
(load "tests/routine-generator.clp")
(test-routine-generator)
(load "tests/injury-prediction.clp")
(test-injury-prediction)
(load "tests/weight-recommendation.clp")
(test-weight-recommendation)
(focus MAIN)
