
(load "templates.clp")
(load "facts.clp")
(load "input.clp")
(load "rules/full-body.clp")
(load "rules/push-pull-leg.clp")
(load "rules/upper-lower.clp")
(load "rules/workout-split.clp")
(load "rules/exercise-selection.clp")
(reset)